main:
  - name: Accueil
    url: /
    weight: 10
  - name: Projets
    url: /projects/
    weight: 20
  - name: Formation
    url: /#education
    weight: 30
  - name: Compétences
    url: /#skills
    weight: 40
  - name: Expérience
    url: /#experience
    weight: 50
  - name: Contact
    url: /#contact
    weight: 60
